spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=v7JDklDyMoSCacdS9+as9+LoJvdoxxdRwpv4V9B1HY4=
jwt.expiration=36000
refresh.expiration=604800000