spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=v7JDklDyMoSCacdS9+as9+LoJvdoxxdRwpv4V9B1HY4=
jwt.expiration=36000
refresh.expiration=604800000

paypal.base-url=https://api-m.sandbox.paypal.com
paypal.mode=SANDBOX
paypal.client-id=ATcC9tilAzjzk3g6l1qBMo5SmOcOOOVg9HUP_ltuUwEUL3lO0jdz0W1ViZ0EYPVGDSOySFzkqSwRjBzD
paypal.secret-key=ECtpoSyII507uBlZOcSXg--n0cvBCqgYYhhDurUMgJ0egx6NHDbpMjYXM3qXMow7e_S2g7XYBOVIlHkm